KERNEL_SIZE: 40 # 101
image_size: [80, 80, 3] # 256, 256, 3
primary_samples: 1000
backup_samples: 4000
num_epochs: 1000 # 2001
densification_interval: 100 # 300
learning_rate: 0.01
image_file_name: "images/Image-02.png"
display_interval: 20
gradient_threshold: 0.002
gaussian_threshold: 0.002
display_loss: False